### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by larry-tx** [bupy7/yii2-config#4]
When I try to run the migration for this extension, I get the following error message:

```
L:\xampp\htdocs\public_html>php yii migrate/up --migrationPath=@bupy7/config/migrations
Yii Migration Tool (based on Yii v2.0.8)

Total 1 new migration to be applied:
        m150802_175752_init

Apply the above migration? (yes|no) [no]:yes
*** applying m150802_175752_init
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in L:\xampp\htdocs\public_html\vendor\bupy7\yii2-config\models\Config.php:69

Stack trace:
#0 L:\xampp\htdocs\public_html\vendor\bupy7\yii2-config\models\Config.php(69): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', 'L:\\xampp\\htdocs...', 69, Array)
#1 L:\xampp\htdocs\public_html\vendor\bupy7\yii2-config\migrations\m150802_175752_init.php(16): bupy7\config\models\Config::tableName()
#2 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): m150802_175752_init->up()
#3 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m150802_175752_...')
#4 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#5 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#6 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#7 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('up', Array)
#8 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#9 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\console\Application.php(176): yii\base\Module->runAction('migrate/up', Array)
#10 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#11 L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 L:\xampp\htdocs\public_html\yii(27): yii\base\Application->run()
#13 {main}
```

**Comment by bupy7** [comment]
@LarryTX show me your a `config.php`.

**Comment by larry-tx** [comment]
I don't have a config.php. I'm showing my main.php instead. Also, please note that it does not include the alterations for your extension because, in the Usage section of your instructions, you say that the migration should be run **before** altering the configuration for the extension.

``` php
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
    'bootstrap' => [
        'log',
        'gii',
    ],
    'components' => [
        /** 'user' => [
         * 'identityClass' => 'common\models\User',
         * 'enableAutoLogin' => true,
         * ], **/
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],
        'assetManager' => [
            'bundles' => [
                'yii\web\JqueryAsset' => [
                    'sourcePath' => null,
                    'js' => ['//code.jquery.com/jquery-2.2.3.min.js']
                ],
                'yii\bootstrap\BootstrapPluginAsset' => [
                    'sourcePath' => null,
                    'js' => ['//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js']
                ],
                'yii\bootstrap\BootstrapAsset' => [
                    'sourcePath' => null,
                    'css' => ['//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css']
                ],
                [
                    'dmstr\web\AdminLteAsset' => [
                        'skin' => 'skin-green',
                        /**
                         * The available skins are:
                        "skin-blue",
                        "skin-black",
                        "skin-red",
                        "skin-yellow",
                        "skin-purple",
                        "skin-green",
                        "skin-blue-light",
                        "skin-black-light",
                        "skin-red-light",
                        "skin-yellow-light",
                        "skin-purple-light",
                        "skin-green-light"
                         */
                    ],
                ],

            ],
        ],

    ],
    'modules' => [
        // Configuration Yii2-User Backend //
        /*'user' => [
            'class' => 'dektrium\user\Module',
            'enableFlashMessages' => true,
            'enableRegistration' => true,
            'enableUnconfirmedLogin' => true,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['LarryTX']
        ],*/
        'gii' => [
            'class' => 'yii\gii\Module',
        ],
        'dynagrid' => [
            'class' => '\kartik\dynagrid]Module'
        ],
        'gridview' => [
            'class' => 'kartik\grid\Module',
        ],
        'redactor' => 'yii\redactor\RedactorModule',
        'categories' => [
            'class' => 'yiimodules\categories\Module',
        ],
    ],
    'params' => $params,
];
```

**Comment by bupy7** [comment]
@LarryTX Thank's for notice! I fixed it. Step by step with [README](https://github.com/bupy7/yii2-config/blob/master/README.md#usage)
1. configure
2. run migrations

**Comment by larry-tx** [comment]
Unfortunately, it still fails. You probably need to remind folks that they have to add `use yii\filters\AccessControl;` since it's not in the template. After adding that, it fails with this message:

```
L:\xampp\htdocs\public_html>php yii migrate/up --migrationPath=@bupy7/config/migrations
Exception 'ReflectionException' with message 'Class user does not exist'

in L:\xampp\htdocs\public_html\vendor\yiisoft\yii2\di\Container.php:417

```

In the same main.php, I do have:

``` php
'modules' => [
        'user' => [
            'class' => 'dektrium\user\Module',
            'admins' => 'LarryTX',
        ],
```

I'm not sure if that's a conflict with Dektrium/User or not.

**Comment by bupy7** [comment]
@LarryTX Are you can to disable `Dectrium/User` and after run the migration again?

**Comment by larry-tx** [comment]
Actually, that didn't work, either. What did work was commenting out the example you gave for Access Control. With that commented out, everything went fine.

``` php
'config' => [
            'class' => 'bupy7\config\Module',
            'enableCaching' => !YII_DEBUG,
            /*'as access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],*/
        ],
```
